/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as LSlugRouteImport } from './routes/l.$slug'
import { Route as AppWhatsappRouteImport } from './routes/_app/whatsapp'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRemindersRouteImport } from './routes/_app/reminders'
import { Route as AppOpportunitiesRouteImport } from './routes/_app/opportunities'
import { Route as AppNetworkRouteImport } from './routes/_app/network'
import { Route as AppLandingsRouteImport } from './routes/_app/landings'
import { Route as AppExportsRouteImport } from './routes/_app/exports'
import { Route as AppEmailRouteImport } from './routes/_app/email'
import { Route as AppDuplicatesRouteImport } from './routes/_app/duplicates'
import { Route as AppContactsRouteImport } from './routes/_app/contacts'
import { Route as AppSettingsUsersRouteImport } from './routes/_app/settings/users'
import { Route as AppSettingsTenantOnboardingRouteImport } from './routes/_app/settings/tenant-onboarding'
import { Route as AppSettingsPipelinesRouteImport } from './routes/_app/settings/pipelines'
import { Route as AppSettingsLeadSourcesRouteImport } from './routes/_app/settings/lead-sources'
import { Route as AppSettingsIntegrationsRouteImport } from './routes/_app/settings/integrations'
import { Route as AppSettingsGeneralRouteImport } from './routes/_app/settings/general'
import { Route as AppSettingsFieldsRouteImport } from './routes/_app/settings/fields'
import { Route as AppSettingsBantRouteImport } from './routes/_app/settings/bant'
import { Route as AppSettingsAuditRouteImport } from './routes/_app/settings/audit'
import { Route as AppSettingsAiAgentRouteImport } from './routes/_app/settings/ai-agent'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const LSlugRoute = LSlugRouteImport.update({
  id: '/l/$slug',
  path: '/l/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRemindersRoute = AppRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRoute,
} as any)
const AppLandingsRoute = AppLandingsRouteImport.update({
  id: '/landings',
  path: '/landings',
  getParentRoute: () => AppRoute,
} as any)
const AppExportsRoute = AppExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailRoute = AppEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AppRoute,
} as any)
const AppDuplicatesRoute = AppDuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsTenantOnboardingRoute =
  AppSettingsTenantOnboardingRouteImport.update({
    id: '/tenant-onboarding',
    path: '/tenant-onboarding',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsPipelinesRoute = AppSettingsPipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsLeadSourcesRoute = AppSettingsLeadSourcesRouteImport.update({
  id: '/lead-sources',
  path: '/lead-sources',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsIntegrationsRoute = AppSettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsGeneralRoute = AppSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsFieldsRoute = AppSettingsFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBantRoute = AppSettingsBantRouteImport.update({
  id: '/bant',
  path: '/bant',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAuditRoute = AppSettingsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAiAgentRoute = AppSettingsAiAgentRouteImport.update({
  id: '/ai-agent',
  path: '/ai-agent',
  getParentRoute: () => AppSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$slug': typeof SlugRoute
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/contacts': typeof AppContactsRoute
  '/duplicates': typeof AppDuplicatesRoute
  '/email': typeof AppEmailRoute
  '/exports': typeof AppExportsRoute
  '/landings': typeof AppLandingsRoute
  '/network': typeof AppNetworkRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/reminders': typeof AppRemindersRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/whatsapp': typeof AppWhatsappRoute
  '/l/$slug': typeof LSlugRoute
  '/settings/ai-agent': typeof AppSettingsAiAgentRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/bant': typeof AppSettingsBantRoute
  '/settings/fields': typeof AppSettingsFieldsRoute
  '/settings/general': typeof AppSettingsGeneralRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/lead-sources': typeof AppSettingsLeadSourcesRoute
  '/settings/pipelines': typeof AppSettingsPipelinesRoute
  '/settings/tenant-onboarding': typeof AppSettingsTenantOnboardingRoute
  '/settings/users': typeof AppSettingsUsersRoute
}
export interface FileRoutesByTo {
  '/$slug': typeof SlugRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/contacts': typeof AppContactsRoute
  '/duplicates': typeof AppDuplicatesRoute
  '/email': typeof AppEmailRoute
  '/exports': typeof AppExportsRoute
  '/landings': typeof AppLandingsRoute
  '/network': typeof AppNetworkRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/reminders': typeof AppRemindersRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/whatsapp': typeof AppWhatsappRoute
  '/l/$slug': typeof LSlugRoute
  '/': typeof AppIndexRoute
  '/settings/ai-agent': typeof AppSettingsAiAgentRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/bant': typeof AppSettingsBantRoute
  '/settings/fields': typeof AppSettingsFieldsRoute
  '/settings/general': typeof AppSettingsGeneralRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/lead-sources': typeof AppSettingsLeadSourcesRoute
  '/settings/pipelines': typeof AppSettingsPipelinesRoute
  '/settings/tenant-onboarding': typeof AppSettingsTenantOnboardingRoute
  '/settings/users': typeof AppSettingsUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$slug': typeof SlugRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/contacts': typeof AppContactsRoute
  '/_app/duplicates': typeof AppDuplicatesRoute
  '/_app/email': typeof AppEmailRoute
  '/_app/exports': typeof AppExportsRoute
  '/_app/landings': typeof AppLandingsRoute
  '/_app/network': typeof AppNetworkRoute
  '/_app/opportunities': typeof AppOpportunitiesRoute
  '/_app/reminders': typeof AppRemindersRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/whatsapp': typeof AppWhatsappRoute
  '/l/$slug': typeof LSlugRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/ai-agent': typeof AppSettingsAiAgentRoute
  '/_app/settings/audit': typeof AppSettingsAuditRoute
  '/_app/settings/bant': typeof AppSettingsBantRoute
  '/_app/settings/fields': typeof AppSettingsFieldsRoute
  '/_app/settings/general': typeof AppSettingsGeneralRoute
  '/_app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/_app/settings/lead-sources': typeof AppSettingsLeadSourcesRoute
  '/_app/settings/pipelines': typeof AppSettingsPipelinesRoute
  '/_app/settings/tenant-onboarding': typeof AppSettingsTenantOnboardingRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$slug'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/contacts'
    | '/duplicates'
    | '/email'
    | '/exports'
    | '/landings'
    | '/network'
    | '/opportunities'
    | '/reminders'
    | '/settings'
    | '/whatsapp'
    | '/l/$slug'
    | '/settings/ai-agent'
    | '/settings/audit'
    | '/settings/bant'
    | '/settings/fields'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/lead-sources'
    | '/settings/pipelines'
    | '/settings/tenant-onboarding'
    | '/settings/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$slug'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/contacts'
    | '/duplicates'
    | '/email'
    | '/exports'
    | '/landings'
    | '/network'
    | '/opportunities'
    | '/reminders'
    | '/settings'
    | '/whatsapp'
    | '/l/$slug'
    | '/'
    | '/settings/ai-agent'
    | '/settings/audit'
    | '/settings/bant'
    | '/settings/fields'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/lead-sources'
    | '/settings/pipelines'
    | '/settings/tenant-onboarding'
    | '/settings/users'
  id:
    | '__root__'
    | '/$slug'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_app/contacts'
    | '/_app/duplicates'
    | '/_app/email'
    | '/_app/exports'
    | '/_app/landings'
    | '/_app/network'
    | '/_app/opportunities'
    | '/_app/reminders'
    | '/_app/settings'
    | '/_app/whatsapp'
    | '/l/$slug'
    | '/_app/'
    | '/_app/settings/ai-agent'
    | '/_app/settings/audit'
    | '/_app/settings/bant'
    | '/_app/settings/fields'
    | '/_app/settings/general'
    | '/_app/settings/integrations'
    | '/_app/settings/lead-sources'
    | '/_app/settings/pipelines'
    | '/_app/settings/tenant-onboarding'
    | '/_app/settings/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SlugRoute: typeof SlugRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  LSlugRoute: typeof LSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/l/$slug': {
      id: '/l/$slug'
      path: '/l/$slug'
      fullPath: '/l/$slug'
      preLoaderRoute: typeof LSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reminders': {
      id: '/_app/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AppRemindersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunities': {
      id: '/_app/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/network': {
      id: '/_app/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/landings': {
      id: '/_app/landings'
      path: '/landings'
      fullPath: '/landings'
      preLoaderRoute: typeof AppLandingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exports': {
      id: '/_app/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof AppExportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/email': {
      id: '/_app/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof AppEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/duplicates': {
      id: '/_app/duplicates'
      path: '/duplicates'
      fullPath: '/duplicates'
      preLoaderRoute: typeof AppDuplicatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/tenant-onboarding': {
      id: '/_app/settings/tenant-onboarding'
      path: '/tenant-onboarding'
      fullPath: '/settings/tenant-onboarding'
      preLoaderRoute: typeof AppSettingsTenantOnboardingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/pipelines': {
      id: '/_app/settings/pipelines'
      path: '/pipelines'
      fullPath: '/settings/pipelines'
      preLoaderRoute: typeof AppSettingsPipelinesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/lead-sources': {
      id: '/_app/settings/lead-sources'
      path: '/lead-sources'
      fullPath: '/settings/lead-sources'
      preLoaderRoute: typeof AppSettingsLeadSourcesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/integrations': {
      id: '/_app/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AppSettingsIntegrationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/general': {
      id: '/_app/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AppSettingsGeneralRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/fields': {
      id: '/_app/settings/fields'
      path: '/fields'
      fullPath: '/settings/fields'
      preLoaderRoute: typeof AppSettingsFieldsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/bant': {
      id: '/_app/settings/bant'
      path: '/bant'
      fullPath: '/settings/bant'
      preLoaderRoute: typeof AppSettingsBantRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/audit': {
      id: '/_app/settings/audit'
      path: '/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AppSettingsAuditRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/ai-agent': {
      id: '/_app/settings/ai-agent'
      path: '/ai-agent'
      fullPath: '/settings/ai-agent'
      preLoaderRoute: typeof AppSettingsAiAgentRouteImport
      parentRoute: typeof AppSettingsRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAiAgentRoute: typeof AppSettingsAiAgentRoute
  AppSettingsAuditRoute: typeof AppSettingsAuditRoute
  AppSettingsBantRoute: typeof AppSettingsBantRoute
  AppSettingsFieldsRoute: typeof AppSettingsFieldsRoute
  AppSettingsGeneralRoute: typeof AppSettingsGeneralRoute
  AppSettingsIntegrationsRoute: typeof AppSettingsIntegrationsRoute
  AppSettingsLeadSourcesRoute: typeof AppSettingsLeadSourcesRoute
  AppSettingsPipelinesRoute: typeof AppSettingsPipelinesRoute
  AppSettingsTenantOnboardingRoute: typeof AppSettingsTenantOnboardingRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAiAgentRoute: AppSettingsAiAgentRoute,
  AppSettingsAuditRoute: AppSettingsAuditRoute,
  AppSettingsBantRoute: AppSettingsBantRoute,
  AppSettingsFieldsRoute: AppSettingsFieldsRoute,
  AppSettingsGeneralRoute: AppSettingsGeneralRoute,
  AppSettingsIntegrationsRoute: AppSettingsIntegrationsRoute,
  AppSettingsLeadSourcesRoute: AppSettingsLeadSourcesRoute,
  AppSettingsPipelinesRoute: AppSettingsPipelinesRoute,
  AppSettingsTenantOnboardingRoute: AppSettingsTenantOnboardingRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppContactsRoute: typeof AppContactsRoute
  AppDuplicatesRoute: typeof AppDuplicatesRoute
  AppEmailRoute: typeof AppEmailRoute
  AppExportsRoute: typeof AppExportsRoute
  AppLandingsRoute: typeof AppLandingsRoute
  AppNetworkRoute: typeof AppNetworkRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRoute
  AppRemindersRoute: typeof AppRemindersRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContactsRoute: AppContactsRoute,
  AppDuplicatesRoute: AppDuplicatesRoute,
  AppEmailRoute: AppEmailRoute,
  AppExportsRoute: AppExportsRoute,
  AppLandingsRoute: AppLandingsRoute,
  AppNetworkRoute: AppNetworkRoute,
  AppOpportunitiesRoute: AppOpportunitiesRoute,
  AppRemindersRoute: AppRemindersRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppWhatsappRoute: AppWhatsappRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SlugRoute: SlugRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  LSlugRoute: LSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
